# Site settings
title: Jonliu Blog
SEOTitle: Jonliu博客 | Jonliu Blog
header-img: img/home-bg.jpg
email: jonliu001922@gmail.com
description: "记录生活、学习的点滴..."
keyword: ""
url: "https://kushao1267.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     "刘小贱还是我zz"
zhihu_username:     "liu-jian-52"
github_username:    "kushao1267"



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: jonliu
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "爱新鲜技术，提升自己"
sidebar-avatar: /img/avatar-jon.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Yunson Blog",
        href: "https://yunsonbai.top"
    },
]
